# -*- coding: utf-8 -*-
"""asinha6_HW4_Q1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YN-UYhtj0rT3HFE29EbMP1Y-flVPr29W
"""

import math
import sys
from prettytable import PrettyTable

def compute_equation(decades, height, weight, dosage, race, enzyme, amiodarone):
    race = race.lower()
    enzyme=enzyme.lower()
    if race == 'asian':
      asian = 1
    else:
      asian = 0
    if race == 'african':
      african = 1
    else:
      african = 0
    if race == 'mixed':
      mixed = 1
    else:
      mixed = 0
    if enzyme in {'carbamazepine', 'phenytoin', 'rifampin', 'rifampicin'}:
      enzyme = 1
    else:
      enzyme = 0
    if amiodarone:
      amiodarone = 1
    else:
      amiodarone = 0

    compute_gene_equation = math.sqrt(dosage) - (5.6044 - 0.2014 * decades + 0.0087 * height + 0.0128 * weight - 0.1092 * asian - 0.2760 * african - 0.1032 * mixed + 1.1816 * enzyme - 0.5503 * amiodarone)

    return compute_gene_equation

def find_gene(gene_equation):
    vkocr_dict = {'VKORC1 A/G': -0.8677, 'VKORC1 A/A': -1.6974, 'VKORC1 U (Unknown)': -0.4854}
    cyp2c9_dict = {'CYP2C9 ∗1/∗2': -0.5211, 'CYP2C9 ∗1/∗3': -0.9357, 'CYP2C9 ∗2/∗2': -1.0616, 'CYP2C9 ∗2/∗3': -1.9206, 'CYP2C9 ∗3/∗3': -2.3312, 'CYP2C9 U (Unknown)': -0.2188}

    minimumvalue = float('inf')
    gene_vkorc1, gene_cyp2cp = '', ''
    for gene1, value1 in vkocr_dict.items():
        for gene2, value2 in cyp2c9_dict.items():
            absdiff = abs(value1 + value2 - gene_equation)
            if absdiff < minimumvalue:
                minimumvalue = absdiff
                gene_vkorc1 = gene1
                gene_cyp2cp = gene2

    return gene_vkorc1, gene_cyp2cp


def main():
    # Set the values for input parameters directly
    age = 74
    decades = age // 10
    height = 167.64
    weight = 80
    dosage = 24.8
    race = 'Asian'
    enzyme = 'carbamazepine'
    amiodarone = True

    gene_equation = compute_equation(decades, height, weight, dosage, race, enzyme, amiodarone)
    gene_vkorc1, gene_cyp2cp = find_gene(gene_equation)

    print(f'Gene Types for Robin: {gene_vkorc1} and {gene_cyp2cp}')

if __name__ == '__main__':
    main()